---
# This role installs and sets up keepalived

- name: Install keepalived (Centos)
  yum: name=keepalived state=present
  when: ansible_os_family == "RedHat"
  tags: keepalived
  notify: restart keepalived

- name: Install keepalived (debian/ubuntu)
  apt: name=keepalived state=latest
  when: ansible_os_family == "Debian"
  tags: keepalived
  notify: restart keepalived

- name: chk_service script shell
  template: 
    src: "{{ keepalived_check_script_name }}.sh.j2 }}"
    dest: "/etc/keepalived/{{ keepalived_check_script_name }}.sh"
    mode: 0755
    owner: root
    group: root
  tags: keepalived
  notify: restart keepalived

- name: Keepalived configuration
  template: 
    src: keepalived.conf.j2 
    dest: /etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=started
  tags: keepalived
